language: ruby
sudo: false
rvm:
- 2.5

addons:
  apt:
    update: true
    packages:
    - python-virtualenv

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

jobs:
  include:
    - stage: test
      script:
      - virtualenv _tmp/virtual
      - . _tmp/virtual/bin/activate
      - pip install docutils pygments
      - bundle exec jekyll build --destination _tmp/brian
      - rm -rf _tmp/virtual
      - bundle exec htmlproofer _tmp --disable-external
      - rm -rf _tmp

    - stage: deploy
      if: branch = master and type = push
      install:
      script:
      - docker build
            --file "Dockerfile"
            --tag "brianmay/penguin_brian:latest"
            --build-arg "BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`"
            --build-arg "VCS_REF=$TRAVIS_COMMIT"
            .
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker push "brianmay/penguin_brian:latest"
      - ./deploy.sh
