language: ruby
sudo: false
rvm:
- 2.5

addons:
  apt:
    update: true
    packages:
    - python-virtualenv

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

script:
- virtualenv _tmp/virtual
- . _tmp/virtual/bin/activate
- pip install docutils pygments
- bundle exec jekyll build --destination _tmp/brian
- rm -rf _tmp/virtual
- bundle exec htmlproofer _tmp --disable-external
- rm -rf _tmp
