name: Build and Deploy to Docker Hub

on: [push, pull_request]

jobs:
  test:
    name: Test valid HTML
    runs-on: ubuntu-latest

    steps:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Australia/Melbourne

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install Jekyll
      run: |-
        gem install bundler
        bundle install

    - name: Build Jekyll
      run: |-
        bundle exec jekyll build --destination _tmp/brian

    - name: Test Result
      run: |-
        rm -rf _tmp/virtual
        bundle exec htmlproofer _tmp --disable-external

    - name: Delete Result
      run: |-
        rm -rf _tmp

  push:
    name: Push
    uses: brianmay/workflows/.github/workflows/docker.yaml@main
    secrets:
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
    needs:
      - test
